//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenVanLang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.MENUs = new HashSet<MENU>();
            this.NOTIFICATIONs = new HashSet<NOTIFICATION>();
            this.ORDERs = new HashSet<ORDER>();
        }
    
        public int ID { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public string EMAIL { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập mật khẩu")]
        [StringLength(50)]
        public string PASSWORD { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập họ tên")]
        public string FULLNAME { get; set; }
        public bool STATUS { get; set; }
        public int ROLE { get; set; }
        [Required(ErrorMessage = "Vui lòng thêm ảnh")]
        public string IMAGE_URL { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập xác nhận mật khẩu")]
        [StringLength(50)]
        [Compare("PASSWORD", ErrorMessage = "Xác nhận mật khẩu không khớp")]
        public string ConfirmPassword { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU> MENUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
    }
}
