//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenVanLang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORY()
        {
            this.FOODs = new HashSet<FOOD>();
        }
    
        public int ID { get; set; }
        public string CATEGORY_CODE { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên loại món ăn")]
        [MinLength(3, ErrorMessage = "Số lượng ký tự tối thiểu là 3")]
        [MaxLength(50, ErrorMessage = "Số lượng ký tự tối đa là 50")]
        public string CATEGORY_NAME { get; set; }
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOOD> FOODs { get; set; }
    }
}
