//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenVanLang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.ORDERs = new HashSet<ORDER>();
        }
    
        public int ID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string FULLNAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public bool STATUS { get; set; }
        public int MEMBER_TYPE { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> FACULTY_ID { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
    }
}
