//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenVanLang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.ORDER_DETAIL = new HashSet<ORDER_DETAIL>();
        }
    
        public int ID { get; set; }
        public string MENU_CODE { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập giá")]
        [Range(0, 1000000, ErrorMessage = "Giá chỉ bao gồm số và nhỏ hơn 1 000 000. Vui lòng nhập lại.")]
        public int PRICE { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        [Range(0, Int32.MaxValue, ErrorMessage = "Số lượng chỉ bao gồm số. Vui lòng nhập lại.")]
        public int QUANTITY { get; set; }

        [DisplayFormat(DataFormatString = "{mm/dd/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Vui lòng chọn ngày")]
        public System.DateTime DATE { get; set; }
        public bool STATUS { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn món ăn")]
        public int FOOD_ID { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual FOOD FOOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAIL> ORDER_DETAIL { get; set; }
    }
}
